services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: ${APP_ENV}
      COOKIE_SECRET: ${COOKIE_SECRET}
      SUPERADMIN_USERNAME: ${SUPERADMIN_USERNAME}
      SUPERADMIN_PASSWORD: ${SUPERADMIN_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      FRONTEND_URL: ${FRONTEND_URL}
      SERVER_URL: ${SERVER_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      EMAIL_AUTH_USER: ${EMAIL_AUTH_USER}
      EMAIL_AUTH_PASSWORD: ${EMAIL_AUTH_PASSWORD}
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_HOST: ${TYPESENSE_HOST}
      TYPESENSE_PORT: ${TYPESENSE_PORT}
      TYPESENSE_PROTOCOL: ${TYPESENSE_PROTOCOL}
      TYPESENSE_URL: ${TYPESENSE_URL}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_SUBS_SECRET: ${STRIPE_SUBS_SECRET}
      STRIPE_CONNECT_SECRET: ${STRIPE_CONNECT_SECRET}
    ports:
      - "3000:3000"
volumes:
  db_data:
    driver: local
